#! /bin/bash/
ko=$(date +%H)
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /home/guty/.k9/ii/54rgfed2
touch /home/guty/.k9/ii/54rgfed2
echo '#! /bin/bash/' >> /home/guty/.k9/ii/54rgfed2


#echo "az='\033[34m'" >> /home/guty/.k9/ii/54rgfed2

#echo "clear" >> /home/guty/.k9/ii/54rgfed2
#echo "azz=$(echo '\e[34m')" >> /home/guty/.k9/ii/54rgfed2

echo "alias 00='echo "$fin$cy🌙ΛＭ"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 01='echo "$fin$azu🌜₳₥"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 02='echo "$fin$cy🌔ΛＭ"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 03='echo "$fin$cy🌑₳₥"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 04='echo "$fin$cy🌙ΛＭ"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 05='echo "$fin$pur🌠₳₥"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 06='echo "$fin$cy🌄ΛＭ"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 07='echo "$fin$pur🌞₳₥"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 08='echo "$fin$pur🔅ΛＭ"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 09='echo "$fin$ama⛅₳₥"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 10='echo "$fin$ver🌞ΛＭ"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 11='echo "$fin₳m🌞"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 12='echo "$ama🌞þM"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 13='echo "$ama⛅卩爪"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 14='echo "$ama🌞þM"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 15='echo "$ama⛅卩爪"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 16='echo "$ama🌞þM"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 17='echo "$ama⛅卩爪"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 18='echo "$pur🌇þM"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 19='echo "$azu🌜卩爪"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 20='echo "$azu🌙þM"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 21='echo "$azu🌛卩爪"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 22='echo "$azu🌜þM"'" >> /home/guty/.k9/ii/54rgfed2
echo "alias 23='echo "$azu🌘卩爪"'" >> /home/guty/.k9/ii/54rgfed2


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /home/guty/.k9/ii/54rgfed2
sh /home/guty/.k9/ii/54rgfed2
rm -f /home/guty/.k9/ii/54rgfed2

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /home/guty/.k9/ii/pam
#cat pam
#sed '1d' /home/guty/.k9/ii/pam





#EOF


#}






#ali
