#! /bin/bash/
ko=$(date +%H)
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /xg/0r/.betas/i/frf32f0
touch /xg/0r/.betas/i/frf32f0
echo '#! /bin/bash/' >> /xg/0r/.betas/i/frf32f0


#echo "az='\033[34m'" >> /xg/0r/.betas/i/frf32f0

#echo "clear" >> /xg/0r/.betas/i/frf32f0
#echo "azz=$(echo '\e[34m')" >> /xg/0r/.betas/i/frf32f0

#shs#        green, red, blue, white, yellow, cyan, magenta  black.


echo "alias 12='cat /xg/0r/.betas/i/bandesiert2'" >> /xg/0r/.betas/i/frf32f0
echo "alias 13='cat /xg/0r/.betas/i/bandesiert2'" >> /xg/0r/.betas/i/frf32f0
echo "alias 14='cat /xg/0r/.betas/i/bandesiert22'" >> /xg/0r/.betas/i/frf32f0
echo "alias 15='cat /xg/0r/.betas/i/bandesiert2'" >> /xg/0r/.betas/i/frf32f0
echo "alias 16='cat /xg/0r/.betas/i/bandesiert22'" >> /xg/0r/.betas/i/frf32f0
echo "alias 17='cat /xg/0r/.betas/i/bandesiert22'" >> /xg/0r/.betas/i/frf32f0



#alias llo='echo -e "$az NOCHE" '


echo $ko >> /xg/0r/.betas/i/frf32f0
sh /xg/0r/.betas/i/frf32f0
rm -f /xg/0r/.betas/i/frf32f0

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











