#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'

clxx="$(sh /xg/0r/.betas/i/colorr)"
c00l="$(sh /xg/0r/.betas/i/color)"
#----------------------------------
#echo " $c00l"
#echo " $fin"
echo " $gri"
cat /xg/0r/.betas/bann/banmadru1-2
echo " $clxx"
cat /xg/0r/.betas/bann/banmadru1-1
echo "$fin"