#! /bin/bash/
ko=$(date +%H)
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
pur0='\033[1;35m'

r0s='\033[45m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /xg/0r/.betas/i/koox
touch /xg/0r/.betas/i/koox
echo '#! /bin/bash/' >> /xg/0r/.betas/i/koox


#echo "az='\033[34m'" >> /xg/0r/.betas/i/koox

#echo "clear" >> /xg/0r/.betas/i/koox
#echo "azz=$(echo '\e[34m')" >> /xg/0r/.betas/i/koox

echo "alias 00='cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 01=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 02='cat /xg/0r/.betas/bann/bann1craven'" >> /xg/0r/.betas/i/koox
echo "alias 03='cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 04='cat /xg/0r/.betas/bann/bann1craven'" >> /xg/0r/.betas/i/koox
echo "alias 05=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 06='cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 07=' cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 08=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 09=' cat /xg/0r/.betas/bann/bann1craven'" >> /xg/0r/.betas/i/koox
echo "alias 10=' cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 11=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 12=' cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 13=' cat /xg/0r/.betas/bann/bann1craven'" >> /xg/0r/.betas/i/koox
echo "alias 14=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 15=' cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 16=' cat /xg/0r/.betas/bann/bann1craven'" >> /xg/0r/.betas/i/koox
echo "alias 17=' cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 18=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 19=' cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 20=' cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox
echo "alias 21=' cat /xg/0r/.betas/bann/bann1craven'" >> /xg/0r/.betas/i/koox
echo "alias 22='cat /xg/0r/.betas/bann/bann2c'" >> /xg/0r/.betas/i/koox
echo "alias 23='cat /xg/0r/.betas/bann/bann3c'" >> /xg/0r/.betas/i/koox


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /xg/0r/.betas/i/koox
sh /xg/0r/.betas/i/koox
rm -f /xg/0r/.betas/i/koox

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











