#! /bin/bash/
ko="$(date +%a)"
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /xg/0r/.betas/i/aliaz
touch /xg/0r/.betas/i/aliaz
echo '#! /bin/bash/' >> /xg/0r/.betas/i/aliaz


#echo "az='\033[34m'" >> /xg/0r/.betas/i/aliaz

#echo "clear" >> /xg/0r/.betas/i/aliaz
#echo "azz=$(echo '\e[34m')" >> /xg/0r/.betas/i/aliaz

echo "alias lun='echo "𝐋 u ℕ Σ s"'" >> /xg/0r/.betas/i/aliaz
echo "alias mar='echo "爪 a Ꞅ t ｅ Ƨ"'" >> /xg/0r/.betas/i/aliaz
echo "alias mié='echo "M I Σ Я c Ө L Σ S"'" >> /xg/0r/.betas/i/aliaz
echo "alias jue='echo "J υ є v є ѕ"'" >> /xg/0r/.betas/i/aliaz
echo "alias vie='echo "V I Σ Я П Σ Ƨ"'" >> /xg/0r/.betas/i/aliaz
echo "alias sáb='echo "Ｓａｂａｄｏ"'" >> /xg/0r/.betas/i/aliaz
echo "alias dom='echo "D Ꝋ m ɨ ᑎ G ɵ"'" >> /xg/0r/.betas/i/aliaz

#alias llo='echo -e "$az NOCHE" '


echo $ko >> /xg/0r/.betas/i/aliaz
sh /xg/0r/.betas/i/aliaz
rm -f /xg/0r/.betas/i/aliaz

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali



