#! /bin/bash/
ko="$(date +%b)"
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /xg/0r/.betas/i/54rty
touch /xg/0r/.betas/i/54rty
echo '#! /bin/bash/' >> /xg/0r/.betas/i/54rty


#echo "az='\033[34m'" >> /xg/0r/.betas/i/54rty

#echo "clear" >> /xg/0r/.betas/i/54rty
#echo "azz=$(echo '\e[34m')" >> /xg/0r/.betas/i/54rty

echo "alias ene='echo "乇 ｎ ｅ Ꞅ Ꝋ"'" >> /xg/0r/.betas/i/54rty
echo "alias feb='echo "千 e ฿ Ꞅ Σ 尺 𝐎"'" >> /xg/0r/.betas/i/54rty
echo "alias mar='echo "爪 ａ Я ｚ Ө"'" >> /xg/0r/.betas/i/54rty
echo "alias abr='echo "Λ ｂ ｒ ｉ ｌ"'" >> /xg/0r/.betas/i/54rty
echo "alias may='echo "爪 ａ ｙ Ꝋ "'" >> /xg/0r/.betas/i/54rty
echo "alias jun='echo "ᒍ ᑌ ᑎ I O"'" >> /xg/0r/.betas/i/54rty
echo "alias jul='echo "ᒍ ᑌ ᒪ I Ꝋ"'" >> /xg/0r/.betas/i/54rty
echo "alias ago='echo "Λ ｇ ｏ ｓ ｔ ｏ"'" >> /xg/0r/.betas/i/54rty
echo "alias sep='echo "Ｓ E ᑭ T I E 爪 B Я Σ"'" >> /xg/0r/.betas/i/54rty
echo "alias oct='echo "ㄖ 匚 ㄒ ㄩ 乃 尺 乇"'" >> /xg/0r/.betas/i/54rty
echo "alias nov='echo "ᑎ Ꝋ ᐯ ɨ E 爪 Ɓ Я 乇"'" >> /xg/0r/.betas/i/54rty
echo "alias dic='echo "Ð I ᄃ I 乇 M B 尺 Σ"'" >> /xg/0r/.betas/i/54rty
#alias llo='echo -e "$az NOCHE" '


echo $ko >> /xg/0r/.betas/i/54rty
sh /xg/0r/.betas/i/54rty
rm -f /xg/0r/.betas/i/54rty

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali



