#! /bin/bash/
ko=$(date +%H)
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /xg/0r/.betas/i/0oo0o
touch /xg/0r/.betas/i/0oo0o
echo '#! /bin/bash/' >> /xg/0r/.betas/i/0oo0o


#echo "az='\033[34m'" >> /xg/0r/.betas/i/0oo0o

#echo "clear" >> /xg/0r/.betas/i/0oo0o
#echo "azz=$(echo '\e[34m')" >> /xg/0r/.betas/i/0oo0o

#shs#        green, red, blue, white, yellow, cyan, magenta  black.

echo "alias 00='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 01='sh /xg/0r/.betas/bann/bann-mmadrugada'" >> /xg/0r/.betas/i/0oo0o
echo "alias 02='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 03='sh /xg/0r/.betas/bann/bann-mmadrugada'" >> /xg/0r/.betas/i/0oo0o
echo "alias 04='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 05='sh /xg/0r/.betas/bann/bann-mmadrugada'" >> /xg/0r/.betas/i/0oo0o
echo "alias 06='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 07='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 08='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 09='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 10='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 11='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 12='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 13='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 14='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 15='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 16='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 17='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 18='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 19='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 20='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 21='sh /xg/0r/.betas/bann/bann-mmadrugada'" >> /xg/0r/.betas/i/0oo0o
echo "alias 22='sh /xg/0r/.betas/i/ban09marz'" >> /xg/0r/.betas/i/0oo0o
echo "alias 23='sh /xg/0r/.betas/bann/bann-mmadrugada'" >> /xg/0r/.betas/i/0oo0o


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /xg/0r/.betas/i/0oo0o
sh /xg/0r/.betas/i/0oo0o
rm -f /xg/0r/.betas/i/0oo0o

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











