#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'
############


clxx="$(sh /xg/0r/.betas/i/colorr)"
clx="$(sh /xg/0r/.betas/i/color)"
########     Fin Colores ##############----

#------------------------------------------------------------

#########   Fechas/hora   ############
#   diasem="$(date +%A)"
#   mes="$(date +%B)"
#   diafech="$(date +%e)"
#   ttime="$(date +'%I:%M')"
#   ye="$(date +%Y)"
######################################

#-------------------------------------------

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"
#   ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#   ant3=`netstat -r | grep "default" | awk {'print $8'}`
#   nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#   routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################
lika1="$(uname -v|cut -d' ' -f3-5)"

lika2="$(uname -o)"

lika3="$(uname -m)"


mem1="$(free -h | sed -n '2p'|cut -d' ' -f11)"
mem2="$(free -h | sed -n '2p'|cut -d' ' -f18)"
mem3="$(free -h | sed -n '2p'|cut -d' ' -f25)"
mem4="$(free -h | sed -n '2p'|cut -d' ' -f39)"
#
dd1="$(df -h | sed -n '4p'|cut -d' ' -f9)"     > /dev/null 2>&1
dd3="$(df -h | sed -n '4p'|cut -d' ' -f14-15)" > /dev/null 2>&1
dd2="$(df -h | sed -n '4p'|cut -d' ' -f12-13)" > /dev/null 2>&1
dd4="$(df -h | sed -n '4p'|cut -d' ' -f16-17)" > /dev/null 2>&1



inici0 () {
	echo ""
clear
echo "

 
          [$roj$lika1 > $lika2-$lika3$fin]



▐▓█▀▀▀▀▀▀▀▀▀█▓▌░▄▄▄▄▄░ ┌─\033[1;33mMɆ₥ØⱤł₳>尺卂爪:::$fin  
▐▓█░░░░▀▄░░░█▓▌░█▄▄▄█░ └┤\033[91m₮Ø₮₳Ⱡ:$fin$mem1 
▐▓█░░░▀▀▀░░░█▓▌░█▄▄▄█░ \033[91mɄ₴₳₦ĐØ:$fin$mem2  
▐▓█▄▄▄▄▄▄▄▄▄█▓▌░█████░ \033[91m₴ł₦ Ʉ₴₳Ɽ:$fin$mem3 
    ▄▄███▄▄    ░█████░ \033[33mB₳₴ɄⱤ₳ ₵₳₵ⱧɆ:$fin$mem4

\033[1;33mᴅɪꜱᴄᴏ|ᴅᴜʀᴏ$fin┌─\033[36m Total::$fin$dd1β | \033[36mUsado::$fin$dd2β❗$dd4                       
          └┤$ver Espacio Libre::$fin$dd3β

"
} 

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################

#   if [ $varr = "1" ]; then
# clear
# 	 echo "
# 
# "
# else
# echo ""
# fi
inici0
