#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
bla='\e[1;97m'
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----
echo ""

echo ""
iip="$(curl ifconfig.co)" > /dev/null 2>&1
ips="$(ip route show|grep ' src ' |cut -d' ' -f9)"
clear
echo ""


#echo ""
#echo ""
#echo  "\e[1;33m   ... Ip Local  ...                 \e[0m"
#echo  "        [\e[34m$ips\e[0m]   "
                                 
echo ""
#ip r
#ifconfig wlan1
#ifconfig wlan0
echo "


                          
$roj▒█▀▀▀█ █▀▀█ █▀▀ █▀▀ █▀▀▄$ama ▀▀█▀▀ █▀▀ █▀▀ ▀▀█▀▀ $fin 
$roj░▀▀▀▄▄ █░░█ █▀▀ █▀▀ █░░█$ama ░▒█░░ █▀▀ ▀▀█ ░░█░░ $fin 
$roj▒█▄▄▄█ █▀▀▀ ▀▀▀ ▀▀▀ ▀▀▀░$ama ░▒█░░ ▀▀▀ ▀▀▀ ░░▀░░ $fin

$fin
"
#echo  "\e[1;33m  ...  IP Publica    ...          \e[0m"
echo  "\e[1;33m    ###>IP Local: \e[0m[\e[34m$ips\e[0m]    ||    \e[1;33m###>IP Publica: \e[0m[\e[34m$iip\e[0m]"
echo ""
echo ""

echo "   \e[1;31m                        ƬΣƧƬ DΣ VΣᄂӨᄃIDΛD     \e[0m "
echo ""
#speedtest-cli

