#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'
######### colores especiales ###########
clx="$(sh /xg/0r/.betas/i/color)"
clxx="$(sh /xg/0r/.betas/i/colorr)"

########     Fin Colores ##############----
echo "
  


 
                       🇲​​​​​  🇵 ​​​​​ 🇻​​​​​ 
$clxx


            尺 乇 卩 尺 ㄖ Đ ㄩ 匚 | 乇 几 Đ ㄖ
$fin

      $roj°°°°°°°°°°°°°°°°°°°°°°$fin
     $roj°°°°°°°°°°°°°°°°°°°°°°°°$fin  
     $roj°°°°°°°°°$fin:;$roj°°°°°°°°°°°°°°$fin  
     $roj°°°°°°°°°$fin:Kdl:$roj°°°°°°°°°°°$fin         ░Λｕｄｉｏ░
     $roj°°°°°°°°°$fin:MNX0xl;$roj°°°°°°°°$fin    
     $roj°°°°°°°°°$fin:MWNXOo:$roj°°°°°°°°$fin           desde
     $roj°°°°°°°°°$fin:N%e:$roj°°°°°°°°°°°$fin     
     $roj°°°°°°°°°$fin:;$roj°°°°°°°°°°°°°°$fin $clx ＹｏｕＴｕｂｅ．ｃｏｍ $roj$fos°$fin
     $roj°°°°°°°°°°°°°°°°°°°°°°°°$fin    
      $roj°°°°°°°°°°°°°°°°°°°°°°$fin
" 


