#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'
############3
azzu="\[$(tput setaf 4)\]"
veer="\[$(tput setaf 2)\]"
cyy="\[$(tput setaf 6)\]"
rooj="\[$(tput setaf 1)\]"
roos="\[$(tput setaf 5)\]"
amma="\[$(tput setaf 3)\]"
blan="\[$(tput setaf 7)\]"
fnn="\[$(tput sgr0)\]"

ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
sleep 0.8s
echo "

丂 乇 尺 ᐯ i Đ ㄖ 尺     🇳​​​​​ 🇬​​​​​ 🇮​​​​​ 🇳​​​​​ 🇽​​​​​     
$roj
       🚫 Ｄｅｓａｃｔｉｖａｄｏ ⛔

$fin
"
