#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#------------------------------------------------------------

#########   Fechas/hora   ############
diasem="$(date +%A)"
mes="$(date +%B)"
diafech="$(date +%e)"
ttime="$(date +'%I:%M')"
ye="$(date +%Y)"
######################################

#-------------------------------------------

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"
#ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#ant3=`netstat -r | grep "default" | awk {'print $8'}`
#nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################


clear
echo "



$roj 
                      ▄████████    ▄████████    ▄████████ 
                      ███    ███   ███    ███   ███    ███ 
                      ███    ███   ███    ███   ███    ███ 
                     ▄███▄▄▄▄██▀   ███    ███  ▄███▄▄▄▄██▀ 
                    ▀▀███▀▀▀▀▀   ▀███████████ ▀▀███▀▀▀▀▀   
                    ▀███████████   ███    ███ ▀███████████ 
                      ███    ███   ███    ███   ███    ███ 
                      ███    ███   ███    █▀    ███    ███ $fin
                  ██$roj  ███    ███                ███    ███ 



$fin



  Ｐｒｅｓｉｏｎａ             ｐａｒａ ﻿Ｃｒｅａｒ $roj R E S P A L D O $fin
                    [$ama$fos ΣПƬΣЯ$fin ] 
"
read eewqew
clear

echo "



$ama
                  ┏━━━┓
                  ┃┏━┓┃
                  ┃┃╋┗┛┏━━┓┏┓┏┓┏━━┓┏━┓┏┓┏┓┏┓┏┓┏━┓
                  ┃┃╋┏┓┃┏┓┃┃┗┛┃┃┏┓┃┃┏┛┣┫┃┗┛┃┣┫┃┏┛
                  ┃┗━┛┃┃┗┛┃┃┃┃┃┃┗┛┃┃┃╋┃┃┃┃┃┃┃┃┃┃
                  ┗━━━┛┗━━┛┗┻┻┛┃┏━┛┗┛╋┗┛┗┻┻┛┗┛┗┛
                  ╋╋╋╋╋╋╋╋╋╋╋╋╋┃┃
                  ╋╋╋╋╋╋╋╋╋╋╋╋╋┗┛

$fin

"

sleep 1s
cd /root
# rm -f /xg/.bashrc
cp /root/.bashrc /xg
cd /opt/ciudad01/deposito
rm -f *
rar a /opt/ciudad01/deposito/respaldo$diafech-$mes-$ye.rar /xg

echo "
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
                             
                             ₵ Ø ₥ ₱ Ɽ Ɇ ₴ ł Ø ₦    ₵ Ø ₥ ₱ Ⱡ Ɇ ₮ ₳ Đ ₳ ! !


$ama

Ａｒｃｈｉｖｏｓ　Ｒｅｓｐａｌｄａｄｏｓ

$fin


                EN: [$azu /opt/ciudad01/deposito/\033[91mrespaldo-$diafech-$mes-$ye.rar $fin]


"
tree /opt/ciudad01/deposito
