#! /bin/bash/
pw="$(pwd)"
ama='\033[33m'

roj='\033[1;31m'

fin='\033[01;37m'


ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"

tim="$(date +99%S)"


clear
echo "


$ama
    ＣｏｎｅＸｉｏｎ  A c t i v a：：：
$fin


          П e T ᑕ a T  -l -vv -p

                $roj
                            
                             匚卄卂ㄒ
$fin"
cat /xg/0r/.betas/bann/xchatban
echo "
$roj
   Ｐｕｅｒｔａ　ｄｅ　Ｅｎｌａｃｅ: $fin nc -vn $ip $tim

"
nc -l -vv -p $tim 
