#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'
############


clxx="$(sh /xg/0r/.betas/i/colorr)"
clx="$(sh /xg/0r/.betas/i/color)"
########     Fin Colores ##############----

#------------------------------------------------------------

#########   Fechas/hora   ############
#   diasem="$(date +%A)"
#   mes="$(date +%B)"
#   diafech="$(date +%e)"
#   ttime="$(date +'%I:%M')"
#   ye="$(date +%Y)"
######################################

#-------------------------------------------

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"
#   ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#   ant3=`netstat -r | grep "default" | awk {'print $8'}`
#   nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#   routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################
echo "$az0"

cat /xg/0r/.betas/bann/banncampp
                                                                                  




	echo "$fin"









                                                                                     

echo "
                                  D e s c a r g a n d o::::

                         | Archivos Mp3 Desde:  http://bandcamp.com |





"


#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################

#   if [ $varr = "1" ]; then
# clear
# 	 echo "
# 
# "
# else
# echo ""
# fi

