#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'
############3
azzu="\[$(tput setaf 4)\]"
veer="\[$(tput setaf 2)\]"
cyy="\[$(tput setaf 6)\]"
rooj="\[$(tput setaf 1)\]"
roos="\[$(tput setaf 5)\]"
amma="\[$(tput setaf 3)\]"
blan="\[$(tput setaf 7)\]"
fnn="\[$(tput sgr0)\]"


 clxx="$(sh /xg/0r/.betas/i/colorr)"
 clx="$(sh /xg/0r/.betas/i/color)"
########     Fin Colores ##############----

#------------------------------------------------------------

#########   Fechas/hora   ############
#   diasem="$(date +%A)"
#   mes="$(date +%B)"
#   diafech="$(date +%e)"
#   ttime="$(date +'%I:%M')"
#   ye="$(date +%Y)"
######################################
rel="$(sh /xg/0r/.betas/bann/reloj-color)"
tty-clock -C $rel -t -c -S
#-------------------------------------------
#########   Fechas/hora   ############
#diasem="$(date +%A)"
diasem="$(sh /xg/0r/.betas/i/dias)"
#mes="$(date +%B)"
mes="$(sh /xg/0r/.betas/i/meses)"
diafech="$(date +%e)"
timme="$(date +'%I:%M')"
#timme="$(date +'%I:%M'|toilet -f future)"
ye="$(date +%Y)"
########################### ip/red ####################
#ipp="$(curl ifconfig.co)"
#   ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#   ant3=`netstat -r | grep "default" | awk {'print $8'}`
#   nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#   routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################
date +'%I:%M'|toilet -f future >> ll
t1="$(sed -n 1p ll)"
t2="$(sed -n 2p ll)"
t3="$(sed -n 3p ll)"
rm -f ll



k44="$(sh /xg/0r/.betas/i/pm-am2)"
ipp="$(curl ifconfig.me)" > /dev/null 2>&1
ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
ant3=`netstat -r | grep "default" | awk {'print $8'}`
nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#
temxm=$(touch tem && curl wttr.in/Morelia,Mexico?lang=es|sed -n '3p'|cut -d' ' -f14-29 > tem && cat tem && rm -f tem) > /dev/null 2>&1
#
#temm=$(touch tem && curl wttr.in/Morelia,Mexico?0|sed -n '4p'|cut -d' ' -f13-14 > tem && cat tem && rm -f tem)
#temm=$(touch tem && curl wttr.in/Morelia,Mexico?0|sed -n '4p'|cut -d' ' -f10-11 > tem && cat tem && rm -f tem)
temm=$(touch tem && curl wttr.in/Morelia,Mexico?0|sed -n '4p'|cut -d' ' -f9-15 > tem && cat tem && rm -f tem) > /dev/null 2>&1

inici0 () {
	echo ""
clear
echo "
       $fin 
                           📡$fin[$roj$ant3$fin]             
  $ama W_ī_Ƒ_ī:$fin $nomred$fin             
                  
 🏠 $roj$ip $fin  $ama Rðµ†êr$fin:: $ro2$routt$fin 
  
$clx
                                    ________________________      |      
                                   |  ________   _________  |     |      
                                   | |$fin .  $clx   | |$fin.   __ $clx | |     |      
                                   | |$fin  *$clx    | |$fin  ,°,.*.$clx| |     |      
                                   | |$fin     .$clx | |$fin :-.-/._$clx| |     |      
               $clxx$t1$clx     | | $fin    .$clx | |$fin :) _° .$clx| |     |      
               $clxx$t2$clx     | | $fin *$clx    | |$fin  °:_)_-$clx| |     |      
               $clxx$t3$clx     | |________| |_________| |     |      
               $k44$clx    |  ________   _________  |     |      
                                   | |        | |         | |     |      
                                   | |$fin°$clx   $fin,$clx | |   $fin.*$clx   | |     |      
                                   | |        | |         | |     |      
                                   | |   $fin.  °$clx| |     $fin.$clx  | |     |      
                                   | |$fin*$clx      | | $fin°$clx      | |     |      
                                   | |________| |_________| |     |      
                                   |________________________|     |      
                                                                  |      
            $clxx$diasem 🔹 $fin$diafech$fin                                                          
                                                            $clx     |$fin
$mes 🔹 $cy0$ye$clxx           $temm $temxm $clx
                                                                  |      
__________________________________________________________________|$fin"
cat /xg/0r/.betas/bann/bann-madrugada1
} 

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################

#   if [ $varr = "1" ]; then
# clear
# 	 echo "
# 
# "
# else
# echo ""
# fi
inici0