#! /bin/bash/
############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[1;31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'
gri="$(tput setaf 8)"
cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[1;4m'
fos='\e[5m'
#gri='\e[2m'

fin='\e[0m'
############3
azzu="\[$(tput setaf 4)\]"
veer="\[$(tput setaf 2)\]"
cyy="\[$(tput setaf 6)\]"
rooj="\[$(tput setaf 1)\]"
roos="\[$(tput setaf 5)\]"
amma="\[$(tput setaf 3)\]"
blan="\[$(tput setaf 7)\]"
fnn="\[$(tput sgr0)\]"


clxx="$(sh /xg/0r/.betas/i/colorr)"
clx="$(sh /xg/0r/.betas/i/color)"
########     Fin Colores ##############----

#------------------------------------------------------------

#########   Fechas/hora   ############
#   diasem="$(date +%A)"
#   mes="$(date +%B)"
#   diafech="$(date +%e)"
#   ttime="$(date +'%I:%M')"
#   ye="$(date +%Y)"
######################################

#-------------------------------------------

########################### ip/red ####################
#ipp="$(curl ifconfig.co)"
#   ip="$(ip route show|grep ' src ' |cut -d' ' -f9)"
#   ant3=`netstat -r | grep "default" | awk {'print $8'}`
#   nomred="$(nmcli c|sed -n '2p'|cut -d' ' -f1)"
#ipx=$(hostname -I)
#   routt="$(ip route show|grep ' dhcp '|cut -d' ' -f3)"
#####################################



inici0 () {
	echo ""
clear
echo "clxx



                eeee e    e eeeee  eeee eeeee  
                8  8 8    8 8   8  8    8   8  
                8e   8eeee8 8eee8e 8eee 8eee8e 
                88     88   88   8 88   88   8 
                88e8   88   88eee8 88ee 88   8 
         .........................................$clxx
                             _____                           
                            /     \  __ _____  ___           
                           /  \ /  \|  |  \  \/  /           
                          /    Y    \  |  />    <            
                          \____|__  /____//__/\_ \           
                                  \/            \/ $fin
   
    [ CyberPunk | DarkSynth | SynthWave | Electro-Mix]



"
} 

#read varr

#####################################
#    case $kaos in
#	     a ) clear; banne1;;
#	     z ) sleep 1; exit;;
#	     * ) sleep 1; echo "[1;31m
#  Opción incorrecta";sleep 1; clear; enterchaoss;;
#    esac
####################################

#   if [ $varr = "1" ]; then
# clear
# 	 echo "
# 
# "
# else
# echo ""
# fi
inici0
