#! /bin/bash/
ko=$(date +%H)
#ali () {

############  Colores  #################
rojx='\e[101m'
rojs='\e[41m'
roj='\033[31m'
ro2='\033[91m'

ver='\033[32m'
ver0='\033[1;32m'
ve2='\033[92m'
ve20='\033[1;32m'

ama='\033[33m'
am0='\033[1;33m'

azu='\033[34m'
az0='\033[1;34m'

pur='\033[35m'

cy='\033[36m'
cy0='\033[1;36m'
##---------------
sub='\e[4m'
fos='\e[5m'

fin='\e[0m'
########     Fin Colores ##############----

#                                         /dev/null 2>&1 &
#echo "$az"

#cat << EOF > /xg/0r/.betas/i/aliaz
touch /xg/0r/.betas/i/aliaz
echo '#! /bin/bash/' >> /xg/0r/.betas/i/aliaz


#echo "az='\033[34m'" >> /xg/0r/.betas/i/aliaz

#echo "clear" >> /xg/0r/.betas/i/aliaz
#echo "azz=$(echo '\e[34m')" >> /xg/0r/.betas/i/aliaz

#
#        green, red, blue, white, yellow, cyan, magenta  black.

echo "alias 00='echo "6"'" >> /xg/0r/.betas/i/aliaz
echo "alias 01='echo "5"'" >> /xg/0r/.betas/i/aliaz
echo "alias 02='echo "6"'" >> /xg/0r/.betas/i/aliaz
echo "alias 03='echo "5"'" >> /xg/0r/.betas/i/aliaz
echo "alias 04='echo "4"'" >> /xg/0r/.betas/i/aliaz
echo "alias 05='echo "6"'" >> /xg/0r/.betas/i/aliaz
echo "alias 06='echo "4"'" >> /xg/0r/.betas/i/aliaz
echo "alias 07='echo "0"'" >> /xg/0r/.betas/i/aliaz
echo "alias 08='echo "2"'" >> /xg/0r/.betas/i/aliaz
echo "alias 09='echo "3"'" >> /xg/0r/.betas/i/aliaz
echo "alias 10='echo "8"'" >> /xg/0r/.betas/i/aliaz
echo "alias 11='echo "0"'" >> /xg/0r/.betas/i/aliaz
echo "alias 12='echo "3"'" >> /xg/0r/.betas/i/aliaz
echo "alias 13='echo "1"'" >> /xg/0r/.betas/i/aliaz
echo "alias 14='echo "3"'" >> /xg/0r/.betas/i/aliaz
echo "alias 15='echo "1"'" >> /xg/0r/.betas/i/aliaz
echo "alias 16='echo "3"'" >> /xg/0r/.betas/i/aliaz
echo "alias 17='echo "7"'" >> /xg/0r/.betas/i/aliaz
echo "alias 18='echo "0"'" >> /xg/0r/.betas/i/aliaz
echo "alias 19='echo "4"'" >> /xg/0r/.betas/i/aliaz
echo "alias 20='echo "5"'" >> /xg/0r/.betas/i/aliaz
echo "alias 21='echo "4"'" >> /xg/0r/.betas/i/aliaz
echo "alias 22='echo "6"'" >> /xg/0r/.betas/i/aliaz
echo "alias 23='echo "5"'" >> /xg/0r/.betas/i/aliaz


#alias llo='echo -e "$az NOCHE" '


echo $ko >> /xg/0r/.betas/i/aliaz
sh /xg/0r/.betas/i/aliaz
rm -f /xg/0r/.betas/i/aliaz

#sh TardeXam
#kol=$(date +%H)
#date +%H



#echo " $kol " >> /xg/0r/.betas/i/pam
#cat pam
#sed '1d' /xg/0r/.betas/i/pam





#EOF


#}






#ali











