#! /bin/bash/
apt-get --purge remove zsh -y

apt-get update
apt-get install toilet -y 
apt-get  install asciinema -y 
apt-get install tilda -y

apt-get install cmatrix  htop  tree -y

apt-get install moc -y
apt-get install elinks -y
apt-get install axel -y

# date --set "18:41"
##              https://github.com/claudiodangelis/qrcp/releases    >>   QR
apt-get install tor torsocks -y

apt-get install eog -y

apt-get install nemo moc -y

cd /root/Descargas
wget https://cf1.vuze.com/files/VuzeInstaller.tar.bz2

# Traductor en terminal
wget git.io/trans
chmod +x trans
mv trans /usr/local/bin/traductor
apt-get install translate-shell -y

#convertir Pdf a imagen
apt-get install poppler-utils -y
### USO:   pdftoppm -jpeg documento.pdf Imagenes/
### Se divide en imagenes la visualizacion del PDF

apt-get install gimp -y

apt-get install curl -y
apt-get install bettercap -y
## https://github.com/evilsocket/bettercap.git

# encriptar el disco duro
apt-get  install cryptsetup -y
apt-get install ccrypt -y


#######   Python &   PIP
apt-get install python3 -y
python3 -m pip install -U pip
pip install ffmpeg
pip install youtube-dl
pip install mps-youtube
pip install bandcamp-downloader
pip install mpv
pip install butterfly


### Spotify
curl -sS curl -sS https://download.spotify.com/debian/pubkey_0D811D58.gpg | sudo apt-key add - 
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list
apt-get update && sudo apt-get install spotify-client


# Escritorio y ambiente gnome
apt install kali-desktop-gnome -y